-- EcoTrack baseline schema (TODO-101).
--
-- Generated from the JPA entities by Hibernate's schema exporter, in the
-- POSTGRES dialect, and then used unchanged on H2 as well. That is deliberate
-- and it is the whole reason one file can serve both databases: the only thing
-- the two dialects disagreed about is how an enum column is spelled — H2 has a
-- native `enum (...)`, Postgres writes `varchar ... check (... in ...)` — and
-- the Postgres spelling is valid H2, while the reverse is not. So the portable
-- form is the Postgres one, and there is no {vendor} split to keep in sync.
--
-- This file is the schema as it stood when Flyway was adopted. It is never
-- edited again: a column change is a NEW V-numbered migration next to it, even
-- during development, because Flyway records this file's checksum and refuses
-- to run against a database whose copy differs. `ddl-auto` is `validate`
-- everywhere now, so Hibernate is the thing that checks this file still
-- describes the entities — a mismatch fails at boot, not in production.

-- Tables
create table access_requests (created_at timestamp(6) with time zone not null, created_employee_id bigint, decided_at timestamp(6) with time zone, decided_by_employee_id bigint, expires_at timestamp(6) with time zone not null, id bigint generated by default as identity, verification_code varchar(8) not null, status varchar(16) not null check (status in ('PENDING','APPROVED','REJECTED','EXPIRED','CLAIMED')), assigned_role_name varchar(32), claim_secret_hash varchar(64) not null, device_id varchar(255) not null, device_label varchar(255), full_name varchar(255) not null, primary key (id));
create table amplasare_orders (duration_days integer, igienizari_per_month integer, is_indefinite boolean, quantity integer, id bigint not null, product_id bigint, end_date varchar(255), location_address varchar(255), location_coordinates varchar(255), start_date varchar(255), primary key (id));
create table client (id bigint generated by default as identity, address varchar(255), email varchar(255), phone varchar(255), primary key (id));
create table companies (id bigint not null, admin_name varchar(255), cui varchar(255), name varchar(255), primary key (id));
create table employee_roles (id bigint generated by default as identity, role_name varchar(255) not null unique, primary key (id));
create table employees (id bigint generated by default as identity, county varchar(255), email varchar(255) unique, full_name varchar(255), phone varchar(255), username varchar(255) not null unique, primary key (id));
create table employees_roles_join (employee_id bigint not null, role_id bigint not null, primary key (employee_id, role_id));
create table igienizare_orders (id bigint not null, recurring_plan_id bigint, subscription_id bigint, sanitation_date varchar(255), sanitation_location_address varchar(255), sanitation_location_coordinates varchar(255), primary key (id));
create table individual (id bigint not null, cnp varchar(255), full_name varchar(255), primary key (id));
create table locations (latitude float(53), longitude float(53), id bigint generated by default as identity, address varchar(255), name varchar(255), primary key (id));
create table orders (client_id bigint, date timestamp(6), id bigint generated by default as identity, number bigint not null, contact varchar(255), details varchar(255), order_type varchar(255), primary key (id));
create table products (is_active boolean, price float(53) not null, id bigint generated by default as identity, description varchar(2000), name varchar(255), primary key (id));
create table recurring_igienizari (active boolean, end_date date, frequency_days integer, is_indefinite boolean, last_generated_date date, start_date date, client_id bigint not null, id bigint generated by default as identity, route_id bigint, subscription_id bigint, contact varchar(255), details varchar(255), sanitation_location_address varchar(255), sanitation_location_coordinates varchar(255), primary key (id));
create table ridicare_orders (pickup_quantity integer, id bigint not null, product_id bigint, pickup_date varchar(255), pickup_location_address varchar(255), pickup_location_coordinates varchar(255), pickup_product_name varchar(255), primary key (id));
create table routes (day_of_week integer, employee_id bigint, id bigint generated by default as identity, county varchar(255), name varchar(255), primary key (id));
create table session_retired_tokens (position integer not null, session_id bigint not null, token_hash varchar(64), primary key (position, session_id));
create table sessions (access_token_expires_at timestamp(6) with time zone, created_at timestamp(6) with time zone not null, employee_id bigint not null, expires_at timestamp(6) with time zone not null, id bigint generated by default as identity, last_used_at timestamp(6) with time zone not null, revoked_at timestamp(6) with time zone, access_token_hash varchar(64) unique, refresh_token_hash varchar(64) not null unique, device_label varchar(255), revoked_reason varchar(255), primary key (id));
create table subscriptions (duration_months integer, is_active boolean, is_indefinite boolean, price float(53), visits_per_month integer, id bigint generated by default as identity, description varchar(2000), name varchar(255), type varchar(255) check (type in ('ONE_TIME','RECURRING')), primary key (id));
create table task_photos (id bigint generated by default as identity, task_id bigint not null, description varchar(255), image_url varchar(255) not null, primary key (id));
create table tasks (order_index integer, quantity integer, scheduled_date date, id bigint generated by default as identity, order_id bigint, recurring_plan_id bigint, route_id bigint, scheduled_time timestamp(6), address varchar(255), client_name varchar(255), client_phone varchar(255), contact_person varchar(255), coordinates varchar(255), internal_notes varchar(255), product_name varchar(255), status varchar(255) not null check (status in ('NEW','IN_PROGRESS','COMPLETED','CANCELLED')), type varchar(255) not null check (type in ('PLACEMENT','PICKUP','SANITIZATION','MAINTENANCE')), primary key (id));

-- Indexes
create index idx_access_request_status on access_requests (status);
create index idx_access_request_device on access_requests (device_id);

-- Foreign keys
alter table if exists amplasare_orders add constraint FKidx5porf3f1ukxy3qxnee8pav foreign key (product_id) references products;
alter table if exists amplasare_orders add constraint FKlo4ljhyfgrxmw90xn7vertpvy foreign key (id) references orders;
alter table if exists companies add constraint FKah7f3hrwh05ojc9o8yw3dj8ni foreign key (id) references client;
alter table if exists employees_roles_join add constraint FKijs2ua4kux1l4agou43v18slr foreign key (role_id) references employee_roles;
alter table if exists employees_roles_join add constraint FKic032v1oayls91x1jpfhg5fki foreign key (employee_id) references employees;
alter table if exists igienizare_orders add constraint FKbt0qwhet3blnsnrc2sytrepxf foreign key (recurring_plan_id) references recurring_igienizari;
alter table if exists igienizare_orders add constraint FKr9tuv4q2p35ji9a9l08xlx72m foreign key (subscription_id) references subscriptions;
alter table if exists igienizare_orders add constraint FKh5srwoqmd0ir741n3csbmmsrd foreign key (id) references orders;
alter table if exists individual add constraint FKqjeylb2xxutuk2eqs4gsem36j foreign key (id) references client;
alter table if exists orders add constraint FK17yo6gry2nuwg2erwhbaxqbs9 foreign key (client_id) references client;
alter table if exists recurring_igienizari add constraint FK3b82p92e0g4dvug3bwflic43l foreign key (client_id) references client;
alter table if exists recurring_igienizari add constraint FKev9xxbs5n76usvbu63gdkt0k8 foreign key (route_id) references routes;
alter table if exists recurring_igienizari add constraint FKrifnmql96avku37xaaseurt9n foreign key (subscription_id) references subscriptions;
alter table if exists ridicare_orders add constraint FKpd1vkfwq5yfl2xaq367dj3e72 foreign key (product_id) references products;
alter table if exists ridicare_orders add constraint FK4oh3tvlhqaogc4h0xoaddwi32 foreign key (id) references orders;
alter table if exists routes add constraint FKnws7wbu06sxg89i5rqg7us2fd foreign key (employee_id) references employees;
alter table if exists session_retired_tokens add constraint FK2675y3h5nci0w322ulvroxh6h foreign key (session_id) references sessions;
alter table if exists sessions add constraint FK7ticto9np2xd4gtcgo04qes1s foreign key (employee_id) references employees;
alter table if exists task_photos add constraint FK6fbtr9qy8eg5x5mr4i4a73nqb foreign key (task_id) references tasks;
alter table if exists tasks add constraint FKn304qmduv2vertaty7l916eyl foreign key (order_id) references orders;
alter table if exists tasks add constraint FKnvpm9rp1ludi4oxwlhfw9ub1d foreign key (recurring_plan_id) references recurring_igienizari;
alter table if exists tasks add constraint FKq7u3v30va912d8s2mbaigoqc7 foreign key (route_id) references routes;

